### ISSUE TITLE
不显示用户名和服务器

### ISSUE THREAD

**Issue by lupohan44** [lintx/YinwuChat-Bungeecord#3]
JS 155行改成
onMessage("["+data.server+"]"+data.player+": "+data.message);

**Comment by lintx** [comment]
因为插件重构了，所以需要使用这个版本的插件的话，web版本需要使用旧版本

**Comment by lupohan44** [comment]
那重构后的插件在哪里下载呢

**Comment by lintx** [comment]
https://github.com/lintx/Minecraft-Plugin-YinwuChat
